# Generated by Django 4.0.6 on 2022-09-09 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_customuser_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='about',
            field=models.CharField(default=' ', max_length=1000, verbose_name='About'),
            preserve_default=False,
        ),
    ]
