# Generated by Django 4.0.6 on 2022-09-14 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_reaction_post_post_reactions_reaction_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_reactions',
            field=models.ManyToManyField(blank=True, related_name='reactions', through='blog.Reaction', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('comments', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
