# Generated by Django 4.0.6 on 2022-09-14 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_post_reactions_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comments',
            new_name='post',
        ),
    ]
